name: Teste com etapas

on: [push]

jobs:
  exemplo:
    runs-on: ubuntu-latest
    steps:
      - name: Mensagem inicial
        run: echo "Pipeline iniciado!"

      - name: Criar diretório
        run: mkdir pasta_exemplo

      - name: Criar arquivo
        run: echo "Conteúdo exemplo" > pasta_exemplo/arquivo.txt

      - name: Exibir conteúdo
        run: cat pasta_exemplo/arquivo.txt
